# Generated by Django 3.1.7 on 2021-04-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='tipoAnuncio',
        ),
    ]
