# Generated by Django 3.1.7 on 2021-04-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0004_anuncio_categoria_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
