# Generated by Django 3.1.7 on 2021-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0006_auto_20210416_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='snombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
