# Generated by Django 3.1.7 on 2021-04-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0007_anuncio_snombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='snombre',
        ),
    ]
