# Generated by Django 3.1.7 on 2021-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0008_remove_anuncio_snombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
