# Generated by Django 3.1.7 on 2021-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0015_anuncio_categoria_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(upload_to='anuncios'),
        ),
    ]
