# Generated by Django 3.1.7 on 2021-05-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0016_auto_20210512_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='precio',
            field=models.IntegerField(max_length=8),
        ),
    ]
