# Generated by Django 3.1.7 on 2021-05-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0017_auto_20210512_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
