# Generated by Django 3.1.7 on 2021-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciosCachinaApp', '0018_auto_20210512_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
